sudo: required

dist: trusty

language: node_js

node_js:
  - "10"
install:
  - npm install
env:
  - TASK=test
matrix:
  fast_finish: true
  allow_failures:
script:
  - npm run $TASK

notifications:
  email: false